---
# This file lists the Ansible collections required to run this project.

collections:
  # Required for various community modules.
  - name: community.general
  # Required for CyberArk credential retrieval.
  - name: cyberark.pas